USE sakila;

CREATE TABLE film_poster (
  film_id SMALLINT UNSIGNED NOT NULL,
  poster VARCHAR(255) NOT NULL,
  last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY  (film_id),
  CONSTRAINT `fk_film_poster_film` FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
